# Generated by Django 6.1 on 2026-09-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('rondalla', 'Rondalla'), ('baile', 'Baile galego'), ('gaita', 'Gaita, pandeireta e percusión'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('file', models.FileField(upload_to='scores/%Y/')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
