# Generated by Django 6.1 on 2026-09-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['category', 'title'], 'verbose_name': 'partitura', 'verbose_name_plural': 'partituras'},
        ),
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.CharField(choices=[('rondalla', 'Rondalla'), ('baile', 'Baile galego'), ('gaita', 'Gaita, pandeireta e percusión'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='score',
            name='file',
            field=models.FileField(upload_to='scores/%Y/', verbose_name='ficheiro'),
        ),
        migrations.AlterField(
            model_name='score',
            name='notes',
            field=models.CharField(blank=True, max_length=300, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='score',
            name='title',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='score',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de subida'),
        ),
    ]
