# Generated by Django 6.1 on 2026-09-01 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_score_options_alter_score_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='preview_image',
            field=models.ImageField(blank=True, editable=False, upload_to='scores_previews/%Y/', verbose_name='vista previa'),
        ),
        migrations.AlterField(
            model_name='score',
            name='file',
            field=models.FileField(help_text='Só se admiten ficheiros PDF.', upload_to='scores/%Y/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='ficheiro'),
        ),
    ]
